language: go
go:
  - 1.15.x
os:
  - linux
services:
  - docker

after_success:
  -
before_deploy: |-
  if [ "$TRAVIS_TAG" != "" ]; then
    IMAGE="cccfs/kube-ldap-webhook:$TRAVIS_TAG"
  else
    IMAGE="cccfs/kube-ldap-webhook:dev"
  fi
  docker build \
  -t $IMAGE \
  .

deploy:
- provider: releases
  token: $GITHUB_TOKEN
  name: kube-ldap-webhook $TRAVIS_TAG
  file: kube-ldap-webhook-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    repo: cccfs/kube-ldap-webhook
    tags: true

- provider: script
  script: >-
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    && docker push ${IMAGE}
  skip_cleanup: true
  on:
    tags: true